# Ejemplo con 8-Square

Algoritmo `Breadth-First Search`

In [38]:
# importar dependencias
import numpy as np
from collections import deque
import random

Asi se representa un estado:

In [39]:
def encontrar_cero(matriz):
    """
    Se encuentra el espacio vacío en el estado analizado
    """
    return np.argwhere(matriz == 0)[0]

In [40]:
def calcular_posibles_transiciones(matriz, esp_v):
    filas, columnas = matriz.shape
    a, b = esp_v # a es fila, b es columna.

    lista_transiciones = [
        (a - 1, b),  # arriba
        (a + 1, b),  # abajo
        (a, b - 1),  # izquierda
        (a, b + 1)   # derecha
    ]

    # Se analiza la validez de cada uno de los puntos frontera,
    # según las dimensiones de la matriz
    return [
        pf for pf in lista_transiciones # pf es una tupla.
        if 0 <= pf[0] < filas
        and 0 <= pf[1] < columnas # Si se cumple el and es válido
    ]

In [41]:
# 

def sucesor(matriz, nuevo_espacio_vacio):
    a, b = nuevo_espacio_vacio
    c, d = encontrar_cero(matriz) # Casilla que inicialmente estaba en cero

    matriz_sucesora = matriz.copy()

    matriz_sucesora[c, d] = matriz[a, b] # La casilla que estaba en cero ahora tiene un valor
    matriz_sucesora[a, b] = 0 # Se limpia la casilla de donde se tomó el valor

    return matriz_sucesora # Se retorna la matriz sucesora.

In [42]:
#estado_inicial = np.array([
#    [1, 2, 3],
#    [4, 0, 5],
#    [8, 6, 7]
#])
# Este estado inicial requiere 14 pasos

estado_objetivo = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])


def generar_estado_aleatorio(estado_objetivo, pasos=20):

    # Tomo el estado objetivo
    estado = estado_objetivo.copy()

    # Hago 20 veces:
        # tomar matriz
        # encontrar cero
        # calcular posibles transiciones a partir de espacio vacio
        # tomo una aleatoriamente
        # guardo matriz resultante y repito hasta que pasos llegue a cero
    for _ in range(pasos):

        espacio_vacio = encontrar_cero(estado)

        fronteras = calcular_posibles_transiciones(
            estado,
            espacio_vacio
        )

        posicion = random.choice(fronteras)

        estado = sucesor(
            estado,
            posicion
        )

    return estado

estado_inicial = generar_estado_aleatorio(estado_objetivo)

estado_inicial

array([[0, 1, 3],
       [4, 2, 6],
       [7, 5, 8]])

In [43]:
def bfs():

    estados = deque([(estado_inicial, 0)])

    estados_visitados = {
        tuple(estado_inicial.flatten())
    }

    padres = {}

    while estados:

        # Sacar el primer estado de la cola
        matriz_actual, distancia = estados.popleft()

        # ¿Llegamos al objetivo?
        if np.array_equal(matriz_actual, estado_objetivo):

            print("¡Se halló el estado objetivo!")
            print(f"Se requirieron {distancia} pasos para hallar la solución")

            # Acá se reconstruye la ruta para presentar la forma en que se llegó
            # a la solución objetivo

            solucion = [matriz_actual]
            actual = matriz_actual

            while not np.array_equal(actual, estado_inicial):

                padre = padres[tuple(actual.flatten())]

                solucion.append(padre)

                actual = padre

            # La solución se construyó
            # desde objetivo -> inicial
            solucion.reverse()

            print("\nSOLUCIÓN:")

            for i, estado in enumerate(solucion):

                print(f"\nPaso {i}:")
                print(estado)

            return

        # Encontrar el cero
        espacio_vacio = encontrar_cero(matriz_actual)

        # Calcular movimientos posibles
        transiciones = calcular_posibles_transiciones(
            matriz_actual,
            espacio_vacio
        )

        # Generar sucesores
        for posicion in transiciones:

            nuevo_estado = sucesor(
                matriz_actual,
                posicion
            )

            # Representación para comprobar
            # si ya fue visitado
            estado_nuevo = tuple(
                nuevo_estado.flatten()
            )

            # Evitar estados repetidos
            if estado_nuevo not in estados_visitados:

                estados.append(
                    (nuevo_estado, distancia + 1)
                )

                estados_visitados.add(
                    estado_nuevo
                )

                # Guardar de qué estado proviene
                padres[estado_nuevo] = matriz_actual

    print("No se encontró una solución")


In [44]:
bfs()

¡Se halló el estado objetivo!
Se requirieron 4 pasos para hallar la solución

SOLUCIÓN:

Paso 0:
[[0 1 3]
 [4 2 6]
 [7 5 8]]

Paso 1:
[[1 0 3]
 [4 2 6]
 [7 5 8]]

Paso 2:
[[1 2 3]
 [4 0 6]
 [7 5 8]]

Paso 3:
[[1 2 3]
 [4 5 6]
 [7 0 8]]

Paso 4:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
